export PATH="$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
export ARCHFLAGS="-arch x86_64"
export DOCKER_CERT_PATH=$HOME/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=tcp://boot2docker:2376
export PYENV_ROOT=/usr/local/opt/pyenv
export PLENV_ROOT=/usr/local/opt/plenv
export RBENV_ROOT=/usr/local/var/rbenv
export NODENV_ROOT=/usr/local/var/nodenv
export GOPATH=/usr/local/opt/go/
export SSL_CERT_FILE="$HOME/cert_file.pem"
export CURL_CA_BUNDLE="$HOME/cert_file.pem"
export DEFAULT_USER='cewen'
source "$HOME/.private_env"
