export PATH="$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
export ARCHFLAGS="-arch x86_64"
export PYENV_ROOT=/usr/local/opt/pyenv
export PLENV_ROOT=/usr/local/opt/plenv
export NODENV_ROOT=/usr/local/var/nodenv
export SWIFTENV_ROOT=/usr/local/var/swiftenv
export GOPATH="${HOME}/code/golang"
export GOROOT="/usr/local/opt/go/libexec"
export DEFAULT_USER='cewen'
export LESSOPEN="|pygmentize %s"
export LESS=' -R '
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin
source "$HOME/.private_env"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
