#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

exec git fetch --all
local_hook="$HOME"/.git_template.local/hooks/post-checkout
[ -f "$local_hook" ] && . "$local_hook"

.git/hooks/ctags >/dev/null 2>&1 &
