#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

.git/hooks/ctags >/dev/null 2>&1 &
exec git fetch --all
